baseURL: 'https://www.ultimatexr.io/'
languageCode: en-us
title: UltimateXR
disablePathToLower: true

params:
  latest_version: v0.9.7
  latest_version_download_url: https://github.com/VRMADA/ultimatexr-unity/releases/download/v0.9.7/UltimateXR_0.9.7.unitypackage
  unity_asset_repo_url: https://github.com/VRMADA/ultimatexr-unity
  website_repo_url: https://github.com/VRMADA/ultimatexr.io
  website_contributing_branch: dev
  discord_server_url: https://discord.gg/GXHdneaFjA
  algolia_app_id: es5exujlvc
  google_tag_id: G-MC0JGRZ79C

menu:
  main:
    - identifier: docs
      name: Docs
      url: /docs/getting-started/what-is-ultimatexr
      weight: 10
    - identifier: scripting
      name: API
      url: /api
      weight: 20
    - name: Community
      url: /community
      weight: 30
    - name: Enterprise
      url: 'https://www.vrmada.com/en/contact'
      weight: 40
    - name: About
      url: /about
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
    noClasses: false

module:
  mounts:
    - source: node_modules/@hotwired/turbo/dist
      target: assets/js/lib/turbo
    - source: node_modules/lucide/dist/esm
      target: assets/js/lib/lucide
    - source: assets
      target: assets
