baseURL: 'https://www.ultimatexr.io/'
languageCode: en-us
title: UltimateXR
disablePathToLower: true

params:
  latest_version: v0.9.7
  latest_version_download_url: https://github.com/VRMADA/ultimatexr-unity/releases/download/v0.9.7/UltimateXR_0.9.7.unitypackage
  unity_asset_repo_url: https://github.com/VRMADA/ultimatexr-unity
  website_repo_url: https://github.com/VRMADA/ultimatexr.io
  website_contributing_branch: dev
  discord_server_url: https://discord.gg/GXHdneaFjA
  algolia_app_id: es5exujlvc
  google_tag_id: G-MC0JGRZ79C
  jsmodules:
    application: "js/application.js"
    api: "js/api.js"
    icons: "js/icons.js"
    navigation: "js/navigation.js"
    search: "js/search.js"
    theme: "js/theme.js"
    toc: "js/toc.js"
    trailer: "js/trailer.js"
    components/theme_manager: "js/components/theme_manager.js"
    lucide: "js/lib/lucide.js"
    "@hotwired/turbo": "js/lib/turbo.es2017-esm.js"
    "@hotwired/stimulus": "js/lib/stimulus.js"
    docsearch: "js/lib/docsearch.js"

menu:
  main:
    - identifier: docs
      name: Docs
      url: /docs/getting-started/what-is-ultimatexr
      weight: 10
    - identifier: scripting
      name: API
      url: /api
      weight: 20
    - name: Community
      url: /community
      weight: 30
    - name: Enterprise
      url: 'https://www.vrmada.com/en/contact'
      weight: 40
    - name: About
      url: /about
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
    noClasses: false
